# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'purchase1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_purchase(object):
    def setupUi(self, purchase):
        purchase.setObjectName("purchase")
        purchase.resize(638, 424)
        self.listView = QtWidgets.QListView(purchase)
        self.listView.setGeometry(QtCore.QRect(-20, -20, 831, 511))
        self.listView.setStyleSheet("background-image: url(\"D:/managerment/image/view5.jpg\")")
        self.listView.setObjectName("listView")
        self.label = QtWidgets.QLabel(purchase)
        self.label.setGeometry(QtCore.QRect(280, 60, 72, 15))
        self.label.setObjectName("label")
        self.check_suply = QtWidgets.QPushButton(purchase)
        self.check_suply.setGeometry(QtCore.QRect(240, 120, 141, 28))
        self.check_suply.setObjectName("check_suply")
        self.buy = QtWidgets.QPushButton(purchase)
        self.buy.setGeometry(QtCore.QRect(240, 180, 141, 28))
        self.buy.setObjectName("buy")
        self.conf_list = QtWidgets.QPushButton(purchase)
        self.conf_list.setGeometry(QtCore.QRect(240, 240, 141, 28))
        self.conf_list.setObjectName("conf_list")
        self.exit = QtWidgets.QPushButton(purchase)
        self.exit.setGeometry(QtCore.QRect(240, 300, 141, 28))
        self.exit.setObjectName("exit")



        self.retranslateUi(purchase)
        QtCore.QMetaObject.connectSlotsByName(purchase)

    def retranslateUi(self, purchase):
        _translate = QtCore.QCoreApplication.translate
        purchase.setWindowTitle(_translate("purchase", "purchase"))
        self.label.setText(_translate("purchase", "采购部门"))
        self.check_suply.setText(_translate("purchase", "查询供应商信息"))
        self.buy.setText(_translate("purchase", "零件购买"))
        self.conf_list.setText(_translate("purchase", "确认清单状态"))
        self.exit.setText(_translate('purchase',"退出"))