# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pur_part.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_pur_comp(object):
    def setupUi(self, pur_comp):
        pur_comp.setObjectName("pur_comp")
        pur_comp.resize(638, 424)
        self.listView = QtWidgets.QListView(pur_comp)
        self.listView.setGeometry(QtCore.QRect(-20, -20, 831, 511))
        self.listView.setStyleSheet("background-image: url(\"D:/managerment/image/view5.jpg\")")
        self.listView.setObjectName("listView")
        self.label = QtWidgets.QLabel(pur_comp)
        self.label.setGeometry(QtCore.QRect(270, 30, 72, 15))
        self.label.setObjectName("label")
        self.deal_id = QtWidgets.QLabel(pur_comp)
        self.deal_id.setGeometry(QtCore.QRect(190, 80, 72, 15))
        self.deal_id.setObjectName("deal_id")
        self.project_id = QtWidgets.QLabel(pur_comp)
        self.project_id.setGeometry(QtCore.QRect(190, 120, 72, 15))
        self.project_id.setObjectName("project_id")
        self.supplie_id = QtWidgets.QLabel(pur_comp)
        self.supplie_id.setGeometry(QtCore.QRect(180, 160, 72, 15))
        self.supplie_id.setObjectName("supplie_id")
        self.part_id = QtWidgets.QLabel(pur_comp)
        self.part_id.setGeometry(QtCore.QRect(190, 200, 72, 15))
        self.part_id.setObjectName("part_id")
        self.num = QtWidgets.QLabel(pur_comp)
        self.num.setGeometry(QtCore.QRect(200, 240, 72, 15))
        self.num.setObjectName("num")
        self.phase = QtWidgets.QLabel(pur_comp)
        self.phase.setGeometry(QtCore.QRect(200, 280, 72, 15))
        self.phase.setObjectName("phase")
        self.lineEdit_deal = QtWidgets.QLineEdit(pur_comp)
        self.lineEdit_deal.setGeometry(QtCore.QRect(280, 80, 131, 21))
        self.lineEdit_deal.setObjectName("lineEdit_deal")
        self.lineEdit_project = QtWidgets.QLineEdit(pur_comp)
        self.lineEdit_project.setGeometry(QtCore.QRect(280, 120, 131, 21))
        self.lineEdit_project.setObjectName("lineEdit_project")
        self.lineEdit_supplier = QtWidgets.QLineEdit(pur_comp)
        self.lineEdit_supplier.setGeometry(QtCore.QRect(280, 160, 131, 21))
        self.lineEdit_supplier.setObjectName("lineEdit_supplier")
        self.lineEdit_part = QtWidgets.QLineEdit(pur_comp)
        self.lineEdit_part.setGeometry(QtCore.QRect(280, 200, 131, 21))
        self.lineEdit_part.setObjectName("lineEdit_part")
        self.lineEdit_num = QtWidgets.QLineEdit(pur_comp)
        self.lineEdit_num.setGeometry(QtCore.QRect(280, 240, 131, 21))
        self.lineEdit_num.setObjectName("lineEdit_num")
        self.lineEdit_phase = QtWidgets.QLineEdit(pur_comp)
        self.lineEdit_phase.setGeometry(QtCore.QRect(280, 280, 131, 21))
        self.lineEdit_phase.setObjectName("lineEdit_phase")
        self.pushButton_continue = QtWidgets.QPushButton(pur_comp)
        self.pushButton_continue.setGeometry(QtCore.QRect(170, 330, 93, 28))
        self.pushButton_continue.setObjectName("pushButton_continue")
        self.pushButton_finish = QtWidgets.QPushButton(pur_comp)
        self.pushButton_finish.setGeometry(QtCore.QRect(350, 330, 93, 28))
        self.pushButton_finish.setObjectName("pushButton_finish")

        self.retranslateUi(pur_comp)
        QtCore.QMetaObject.connectSlotsByName(pur_comp)

    def retranslateUi(self, pur_comp):
        _translate = QtCore.QCoreApplication.translate
        pur_comp.setWindowTitle(_translate("pur_comp", "pur_comp"))
        self.label.setText(_translate("pur_comp", "零件购买"))
        self.deal_id.setText(_translate("pur_comp", "交易号"))
        self.project_id.setText(_translate("pur_comp", "工程号"))
        self.supplie_id.setText(_translate("pur_comp", "供应商号"))
        self.part_id.setText(_translate("pur_comp", "零件号"))
        self.num.setText(_translate("pur_comp", "数量"))
        self.phase.setText(_translate("pur_comp", "阶段"))
        self.pushButton_continue.setText(_translate("pur_comp", "购买"))
        self.pushButton_finish.setText(_translate("pur_comp", "返回"))
