# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'project.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_project(object):
    def setupUi(self, project):
        project.setObjectName("project")
        project.resize(638, 424)
        self.listView = QtWidgets.QListView(project)
        self.listView.setGeometry(QtCore.QRect(-20, 0, 831, 511))
        self.listView.setStyleSheet("background-image: url(\"D:/managerment/image/view5.jpg\")")
        self.listView.setObjectName("listView")
        self.label = QtWidgets.QLabel(project)
        self.label.setGeometry(QtCore.QRect(260, 40, 81, 21))
        self.label.setObjectName("label")
        self.make_plan = QtWidgets.QPushButton(project)
        self.make_plan.setGeometry(QtCore.QRect(230, 80, 121, 31))
        self.make_plan.setObjectName("make_plan")
        self.make_list = QtWidgets.QPushButton(project)
        self.make_list.setGeometry(QtCore.QRect(230, 130, 121, 31))
        self.make_list.setObjectName("make_list")
        self.exit = QtWidgets.QPushButton(project)
        self.exit.setGeometry(QtCore.QRect(230, 330, 121, 31))
        self.exit.setObjectName("exit")
        self.update_list = QtWidgets.QPushButton(project)
        self.update_list.setGeometry(QtCore.QRect(230, 180, 121, 31))
        self.update_list.setObjectName("update_list")
        self.update_pace = QtWidgets.QPushButton(project)
        self.update_pace.setGeometry(QtCore.QRect(230, 230, 121, 31))
        self.update_pace.setObjectName("update_pace")
        self.check_proj = QtWidgets.QPushButton(project)
        self.check_proj.setGeometry(QtCore.QRect(230, 280, 121, 31))
        self.check_proj.setObjectName("check_proj")

        self.retranslateUi(project)
        QtCore.QMetaObject.connectSlotsByName(project)

    def retranslateUi(self, project):
        _translate = QtCore.QCoreApplication.translate
        project.setWindowTitle(_translate("project", "Project"))
        self.label.setText(_translate("project", "工程部门"))
        self.make_plan.setText(_translate("project", "制定初始计划"))
        self.make_list.setText(_translate("project", "开出零件清单"))
        self.exit.setText(_translate("project", "退出"))
        self.update_list.setText(_translate("project", "零件清单更新"))
        self.update_pace.setText(_translate("project", "工程阶段更新"))
        self.check_proj.setText(_translate("project", "工程信息查询"))
