# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'supcheck_list.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_supCheck_list(object):
    def setupUi(self, supCheck_list):
        supCheck_list.setObjectName("supCheck_list")
        supCheck_list.resize(638, 424)
        self.listView = QtWidgets.QListView(supCheck_list)
        self.listView.setGeometry(QtCore.QRect(-20, 0, 831, 511))
        self.listView.setStyleSheet("background-image: url(\"D:/managerment/image/view5.jpg\")")
        self.listView.setObjectName("listView")
        self.exit = QtWidgets.QPushButton(supCheck_list)
        self.exit.setGeometry(QtCore.QRect(270, 340, 93, 28))
        self.exit.setObjectName("exit")
        self.tableWidget = QtWidgets.QTableWidget(supCheck_list)
        self.tableWidget.setGeometry(QtCore.QRect(70, 180, 471, 131))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.proj_id = QtWidgets.QLabel(supCheck_list)
        self.proj_id.setGeometry(QtCore.QRect(230, 40, 201, 81))
        self.proj_id.setObjectName("proj_id")
        self.lineEdit_project = QtWidgets.QLineEdit(supCheck_list)
        self.lineEdit_project.setGeometry(QtCore.QRect(310, 70, 121, 21))
        self.lineEdit_project.setObjectName("lineEdit_project")
        self.pushButton_project = QtWidgets.QPushButton(supCheck_list)
        self.pushButton_project.setGeometry(QtCore.QRect(282, 130, 81, 28))
        self.pushButton_project.setObjectName("pushButton_project")

        self.retranslateUi(supCheck_list)
        QtCore.QMetaObject.connectSlotsByName(supCheck_list)

    def retranslateUi(self, supCheck_list):
        _translate = QtCore.QCoreApplication.translate
        supCheck_list.setWindowTitle(_translate("supCheck_list", "supCheck"))
        self.exit.setText(_translate("supCheck_list", "退出"))
        self.proj_id.setText(_translate("supCheck_list", "工程号"))
        self.pushButton_project.setText(_translate("supCheck_list", "查询"))
