# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'supcheck.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_supCheck(object):
    def setupUi(self, supCheck):
        supCheck.setObjectName("supCheck")
        supCheck.resize(638, 424)
        self.listView = QtWidgets.QListView(supCheck)
        self.listView.setGeometry(QtCore.QRect(-20, 0, 831, 511))
        self.listView.setStyleSheet("background-image: url(\"D:/managerment/image/view5.jpg\")")
        self.listView.setObjectName("listView")
        self.label = QtWidgets.QLabel(supCheck)
        self.label.setGeometry(QtCore.QRect(280, 50, 72, 15))
        self.label.setObjectName("label")
        self.exit = QtWidgets.QPushButton(supCheck)
        self.exit.setGeometry(QtCore.QRect(270, 340, 93, 28))
        self.exit.setObjectName("exit")
        self.tableWidget = QtWidgets.QTableWidget(supCheck)
        self.tableWidget.setGeometry(QtCore.QRect(80, 100, 471, 211))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)

        self.retranslateUi(supCheck)
        QtCore.QMetaObject.connectSlotsByName(supCheck)

    def retranslateUi(self, supCheck):
        _translate = QtCore.QCoreApplication.translate
        supCheck.setWindowTitle(_translate("supCheck", "supCheck"))
        self.label.setText(_translate("supCheck", "查询结果"))
        self.exit.setText(_translate("supCheck", "退出"))
