# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'supcheck_suply.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_supCheck_sup(object):
    def setupUi(self, supCheck_sup):
        supCheck_sup.setObjectName("supCheck_sup")
        supCheck_sup.resize(638, 424)
        self.listView = QtWidgets.QListView(supCheck_sup)
        self.listView.setGeometry(QtCore.QRect(-20, 0, 831, 511))
        self.listView.setStyleSheet("background-image: url(\"D:/managerment/image/view5.jpg\")")
        self.listView.setObjectName("listView")
        self.exit = QtWidgets.QPushButton(supCheck_sup)
        self.exit.setGeometry(QtCore.QRect(250, 350, 93, 28))
        self.exit.setObjectName("exit")
        self.tableWidget = QtWidgets.QTableWidget(supCheck_sup)
        self.tableWidget.setGeometry(QtCore.QRect(50, 210, 531, 111))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.project_id = QtWidgets.QLabel(supCheck_sup)
        self.project_id.setGeometry(QtCore.QRect(200, 80, 72, 15))
        self.project_id.setObjectName("project_id")
        self.part_id = QtWidgets.QLabel(supCheck_sup)
        self.part_id.setGeometry(QtCore.QRect(200, 120, 72, 15))
        self.part_id.setObjectName("part_id")
        self.lineEdit_project = QtWidgets.QLineEdit(supCheck_sup)
        self.lineEdit_project.setGeometry(QtCore.QRect(300, 70, 121, 21))
        self.lineEdit_project.setObjectName("lineEdit_project")
        self.lineEdit_part = QtWidgets.QLineEdit(supCheck_sup)
        self.lineEdit_part.setGeometry(QtCore.QRect(300, 120, 121, 21))
        self.lineEdit_part.setObjectName("lineEdit_part")
        self.pushButton_query = QtWidgets.QPushButton(supCheck_sup)
        self.pushButton_query.setGeometry(QtCore.QRect(240, 160, 93, 28))
        self.pushButton_query.setObjectName("pushButton_query")

        self.retranslateUi(supCheck_sup)
        QtCore.QMetaObject.connectSlotsByName(supCheck_sup)

    def retranslateUi(self, supCheck_sup):
        _translate = QtCore.QCoreApplication.translate
        supCheck_sup.setWindowTitle(_translate("supCheck_sup", "supCheck"))
        self.exit.setText(_translate("supCheck_sup", "退出"))
        self.project_id.setText(_translate("supCheck_sup", "工程号"))
        self.part_id.setText(_translate("supCheck_sup", "零件号"))
        self.pushButton_query.setText(_translate("supCheck_sup", "查询"))
